function showTab(id,el){document.querySelectorAll('main').forEach(m=>m.classList.add('hidden'));document.getElementById(id).classList.remove('hidden');document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));el.classList.add('active'); if(id==='mine')renderMine(); if(id==='roommate'){loadRoommateForm();renderRoommates()} if(id==='myMatches')renderMatchRequests();}
function val(id){return document.getElementById(id).value}
function renderListings(){const db=loadDB();const filter=document.getElementById('suburbFilter').value;const items=db.listings.filter(x=>x.status==='approved'&&(filter==='all'||x.suburb===filter));document.getElementById('listingGrid').innerHTML=items.map(x=>card(x,true)).join('')||'<div class="card">暂无已审核房源。</div>'}
function card(x,publicView=false){return `<div class="card"><div class="listing-img">${x.suburb} · ${x.type}</div><div class="row space"><h3>${x.title}</h3><span class="pill ${riskPill(x.risk)}">${x.risk}</span></div><p class="muted">${x.suburb} · $${x.rent}/week · ${x.type}</p><p>${x.desc}</p><div class="row"><span class="pill ${x.status==='approved'?'good':'warn'}">${x.status}</span><span class="pill ${riskPill(x.risk)}">Scam Score: ${x.score??'Pending'}</span>${x.needRoommate?'<span class="pill good">Roommate Match Enabled</span>':''}</div>${x.roommateReq?`<div class="tagrow mini muted">室友偏好：${x.roommateReq.gender} · ${x.roommateReq.school} · ${x.roommateReq.sleep} · ${x.roommateReq.clean}</div>`:''}<details class="section"><summary class="splitlink">查看评分原因</summary><ul>${(x.reasons||[]).map(r=>`<li>${r}</li>`).join('')}</ul></details>${publicView?`<button class="btn" onclick="apply('${x.id}')">申请联系</button>`:''}</div>`}
function submitListing(){const f=id=>document.getElementById(id).files?.[0]?.name||'';const db=loadDB();const need=document.getElementById('needRoommate').checked;const listing={id:'L'+Date.now(),title:val('title')||'Untitled listing',suburb:val('suburb'),rent:Number(val('rent')||0),type:val('type'),desc:val('desc')||'No description yet.',owner:'Current Member',created:new Date().toISOString().slice(0,10),status:'pending',score:null,risk:'Pending Review',reasons:['Waiting for admin document review'],needRoommate:need,roommateReq:need?{gender:val('prefGender'),school:val('prefSchool'),sleep:val('prefSleep'),clean:val('prefClean')}:null,docs:{studentId:f('docStudent'),photoId:f('docPhoto'),lease:f('docLease'),consent:f('docConsent'),bond:f('docBond'),photos:document.getElementById('docPhotos').files.length?document.getElementById('docPhotos').files.length+' photos':'',inspection:f('docInspection'),utility:f('docUtility')}};db.listings.unshift(listing);saveDB(db);alert('已提交后台审核。Admin Console 会看到这条 pending listing；如果开启了 Roommate Match，也会同步生成室友偏好。');renderMine();renderListings()}
function saveRoommateProfile(){const db=loadDB();db.roommateProfile={name:val('rmName')||'Current Member',age:val('rmAge')||'',gender:val('rmGender'),school:val('rmSchool'),major:val('rmMajor'),suburb:val('rmSuburb'),sleep:val('rmSleep'),clean:val('rmClean'),cook:val('rmCook'),smoke:val('rmSmoke'),pet:val('rmPet'),guests:val('rmGuests'),bio:val('rmBio')};saveDB(db);alert('室友匹配资料已保存。');renderRoommates();renderMatchRequests()}
function loadRoommateForm(){const p=loadDB().roommateProfile;if(!p)return;['Name','Age','Gender','School','Major','Suburb','Sleep','Clean','Cook','Smoke','Pet','Guests','Bio'].forEach(k=>{const id='rm'+k;const el=document.getElementById(id);if(el&&p[k.toLowerCase()])el.value=p[k.toLowerCase()]})}
function renderRoommates(){const db=loadDB();const p=db.roommateProfile;const items=db.roommates.map(r=>({...r,match:roommateScore(p,r)})).sort((a,b)=>b.match-a.match);document.getElementById('roommateGrid').innerHTML=items.map(r=>`<div class="card"><div class="row space"><h3>${r.name}</h3><div class="score">${r.match}%</div></div><div class="matchbar"><span style="width:${r.match}%"></span></div><p class="muted">${r.school} · ${r.major} · ${r.suburb}</p><p>${r.profile}</p><div class="tagrow"><span class="pill">${r.sleep}</span><span class="pill">${r.clean}</span><span class="pill">${r.smoke}</span><span class="pill">${r.guests}</span></div><button class="btn ghost section" onclick="requestMatch('${r.id}')">Request Match</button></div>`).join('')}
function requestMatch(id){const db=loadDB();const r=db.roommates.find(x=>x.id===id);db.roommateRequests.unshift({id:'M'+Date.now(),to:id,name:r.name,score:roommateScore(db.roommateProfile,r),status:'sent',created:new Date().toISOString().slice(0,10)});saveDB(db);alert('匹配请求已发送。');renderMatchRequests()}
function renderMatchRequests(){const db=loadDB();document.getElementById('matchRequests').innerHTML=(db.roommateRequests||[]).map(m=>`<div class="card"><h3>${m.name}</h3><div class="score">${m.score}%</div><p class="muted">${m.created} · ${m.status}</p><p>真实上线后，这里会接入站内消息/邮件通知，双方同意后才展示联系方式。</p></div>`).join('')||'<div class="card">暂无匹配请求。先去填写室友匹配资料。</div>'}
function renderMine(){const db=loadDB();document.getElementById('myListings').innerHTML=db.listings.filter(x=>x.owner==='Current Member'||x.owner==='Demo User').map(x=>card(x,false)).join('')||'<div class="card">你还没有提交。</div>'}
function apply(id){const name=prompt('你的名字？'); if(!name)return; const msg=prompt('留言给发布人：')||'I am interested.'; const db=loadDB();db.applications.push({id:'A'+Date.now(),listingId:id,name,message:msg,status:'new'});saveDB(db);alert('已提交申请，后台/发布人可看到。')}
renderListings();renderRoommates();renderMine();renderMatchRequests();
